# Generated by Django 5.2.7 on 2025-10-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del producto (opcional)', null=True, upload_to='productos/'),
        ),
    ]
