# Generated by Django 5.2.7 on 2025-10-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default='2025-10-30'),
            preserve_default=False,
        ),
    ]
